# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DisplayLabel = QtWidgets.QLabel(self.centralwidget)
        self.DisplayLabel.setGeometry(QtCore.QRect(20, 10, 921, 601))
        self.DisplayLabel.setText("")
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(26, 650, 921, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.facedatacollect = QtWidgets.QPushButton(self.layoutWidget)
        self.facedatacollect.setObjectName("facedatacollect")
        self.horizontalLayout.addWidget(self.facedatacollect)
        self.monitor = QtWidgets.QPushButton(self.layoutWidget)
        self.monitor.setObjectName("monitor")
        self.horizontalLayout.addWidget(self.monitor)
        self.terminate = QtWidgets.QPushButton(self.layoutWidget)
        self.terminate.setObjectName("terminate")
        self.horizontalLayout.addWidget(self.terminate)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.facedatacollect.clicked.connect(MainWindow.facedatacollect_Clicked)
        self.monitor.clicked.connect(MainWindow.startMonitoring_Clicked)
        self.terminate.clicked.connect(MainWindow.exit0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "寝室异常进入检测"))
        self.facedatacollect.setText(_translate("MainWindow", "人脸数据录入"))
        self.monitor.setText(_translate("MainWindow", "异常进入检测"))
        self.terminate.setText(_translate("MainWindow", "退出"))
